
LIBRARY ieee;
	USE ieee.std_logic_1164.ALL;

ENTITY ORGATE_HIRA IS
	PORT (
	A : IN STD_LOGIC;
	B : IN STD_LOGIC;
	C : OUT STD_LOGIC
	);
END ORGATE_HIRA;

ARCHITECTURE BEHAVIOUR OF ORGATE_HIRA IS
BEGIN
C <= A OR B;
END BEHAVIOUR;
